server:
  port: 14308
  address: 0.0.0.0

photoLocation: /home/static/picture

spring:
  mvc:
    static-path-pattern: /**      #这个配置是默认配置
  http:                           #这里是访问项目外文件夹的关键
    multipart:
      locations: /home/static
  resources:
    # 资源缓存时间，单位秒
    cache:
      cachecontrol:
        max-age: 604800
    chain:
      cache: true
      compressed: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, file:${spring.http.multipart.locations}
    #需要把自定义的路径添加到static-locations后面,原本的静态访问路径也要加上不然原本的静态资源会访问不到。
    #访问时直接在访问路径上加上profile之后的路径，例如profile中有文件stuImg/test.jpg，则访问路径为localhost/stuImg/test.jpg


  thymeleaf: 
    prefix: classpath:/templates/
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 10000
      max-lifetime: 600000
      idle-timeout: 60000
      validation-timeout: 1000
      leak-detection-threshold: 30000
    #热部署生效
  devtools: 
    restart: 
      enabled: true
      #设置重启的目录
      additional-paths: src/main/
  aop:
    auto: true
    proxy-target-class: true
    
mybatis:
    #实体类所做包
    type-aliases-package: com.ay.demo.entity
    #mapper.xml所在位置
    mapper-locations: classpath:com.sparkle.mapper/*.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
